version: '3.8'
services:
  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASSWORD=P@ssw0rd123
      - DB_NAME=ProyectoMP
      - JWT_SECRET=clave_secreta
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mcr.microsoft.com/mssql/server
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd123
    ports:
      - "1433:1433"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
